name: Deploy to WordPress.org

on:
  release:
    types: [published]  # opzionale: parte quando pubblichi una GitHub Release
  workflow_dispatch:          # avvio manuale dal tab Actions
jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    env:
      SLUG: cityevents          # <-- slug del plugin su wp.org (uguale all’URL SVN)
      BUILD_DIR: build                 # cartella temporanea di build
      PHP_VERSION: '8.3'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from tag
        id: getver
        run: |
          REF="${GITHUB_REF##*/}"          # es. v1.0.0
          VER="${REF#v}"                   # es. 1.0.0
          echo "version=${VER}" >> $GITHUB_OUTPUT

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none
          tools: composer

      - name: Install Composer deps (no dev)
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      # Se usi npm/webpack per assets, aggiungi qui build frontend (npm ci && npm run build)
      # - name: Build assets
      #   run: |
      #     npm ci
      #     npm run build

      - name: Prepare build dir
        run: |
          rm -rf "${BUILD_DIR}"
          mkdir -p "${BUILD_DIR}/${SLUG}"
          rsync -av --delete \
            --exclude-from=".distignore" \
            ./ "${BUILD_DIR}/${SLUG}/"

      # Verifica version matching (opzionale ma utile)
      - name: Check plugin version matches tag
        run: |
          FILE=$(grep -rl "Plugin Name:" "${BUILD_DIR}/${SLUG}" | head -n1)
          if [ -z "$FILE" ]; then
            echo "Impossible trovare il file principale del plugin"; exit 1;
          fi
          # Estrae "Version: x.y.z" dall'header
          PLUGIN_VER=$(php -r '
            $f=$argv[1];
            $s=file_get_contents($f);
            if(preg_match("/^\\s*\\*\\s*Version:\\s*(.+)$/mi",$s,$m)){echo trim($m[1]);}else{exit(1);}
          ' "$FILE")
          echo "Plugin header version: $PLUGIN_VER"
          echo "Git tag version: ${{ steps.getver.outputs.version }}"
          [ "$PLUGIN_VER" = "${{ steps.getver.outputs.version }}" ] || { echo "Version mismatch"; exit 1; }

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          svn_username: ${{ secrets.SVN_USERNAME }}
          svn_password: ${{ secrets.SVN_PASSWORD }}
          slug: ${{ env.SLUG }}
          version: ${{ steps.getver.outputs.version }}
          # Directory da cui prendere i file da pubblicare (deve contenere direttamente i file del plugin)
          build_dir: ${{ env.BUILD_DIR }}/${{ env.SLUG }}
          # Copia le immagini da .wordpress-org/ verso /assets del repo SVN:
          assets_dir: .wordpress-org
